#
# Instructions:
#   1. Copy this file and name it config.yaml.
#   2. Customize the values below.
#   3. Run `npm run generate`
#

# `Plugin Name`
PLUGIN_NAME: 'Plugin Boilerplate'

# Plugin slug. Lowercase. Dashed.
PLUGIN_SLUG: 'plugin-boilerplate'

# `Plugin Description`
PLUGIN_DESCRIPTION: 'About your plugin...'

# `Plugin Version`
PLUGIN_VERSION: '0.0.1'

# @package, Note the underscore
PLUGIN_PACKAGE: 'Plugin_Boilerplate'

# @author and `Author`
PLUGIN_AUTHOR: 'Your Name'

# @link and `Plugin URI`
PLUGIN_URI: 'https://'

# `Author URI`:
PLUGIN_AUTHOR_URI: 'https://'

# @license and `License`
PLUGIN_LICENSE: 'Private'
PLUGIN_LICENSE_URI: ''

# @copyright
COPYRIGHT_YEAR: '2022'
COPYRIGHT_HOLDER: 'Person or Business'

# `Text Domain`:
PLUGIN_TEXT_DOMAIN: 'pluginboilerplate'

# `Requires PHP`
PLUGIN_PHP_VERSION: '7.0'

# PLUGIN_PREFIX is used where the short version
# of the plugin name is required.
PLUGIN_PREFIX: 'BP'